alias carnect='ssh root@178.63.103.132'
alias jens='ssh jens@primitive-visions.de'
alias work='cd  /cygdrive/c/Users/jens/workspace'
alias c:='cd /cygdrive/c/'
alias f:='cd /cygdrive/f/'
alias vm='ssh -X root@192.168.2.180'
alias backup='/cygdrive/c/Users/jens/bin/sync_freeagent_backup.sh'
alias raspi='ssh -X -c arcfour,blowfish-cbc jens@192.168.2.105'
